export const C = {
  bg: "hsl(240,10%,3.9%)",
  fg: "hsl(0,0%,98%)",
  card: "hsl(240,5.9%,6%)",
  sidebar: "hsl(240,5.9%,7%)",
  topbar: "hsl(240,5.9%,6%)",
  border: "hsl(240,3.7%,13%)",
  borderMd: "hsl(240,3.7%,18%)",
  muted: "hsl(240,5%,50%)",
  mutedBg: "hsl(240,3.7%,10%)",
  input: "hsl(240,3.7%,10%)",
  hover: "hsl(240,3.7%,13%)",
  rowHover: "hsl(240,3.7%,7%)",
  green: "hsl(142,71%,55%)",
  greenBg: "hsl(142,71%,8%)",
  greenBorder: "hsl(142,71%,15%)",
  red: "hsl(0,72%,60%)",
  redBg: "hsl(0,72%,12%)",
  redBorder: "hsl(0,72%,22%)",
  yellow: "hsl(45,93%,65%)",
  yellowBg: "hsl(45,93%,10%)",
  yellowBorder: "hsl(45,93%,20%)",
  blue: "hsl(221,83%,65%)",
  blueBg: "hsl(221,83%,10%)",
  blueBorder: "hsl(221,83%,20%)",
  purple: "hsl(270,70%,70%)",
  purpleBg: "hsl(270,70%,10%)",
  purpleBorder: "hsl(270,70%,20%)",
};

export const BADGE_MAP = {
  pending: { bg: C.yellowBg, color: C.yellow, border: C.yellowBorder },
  completed: { bg: C.greenBg, color: C.green, border: C.greenBorder },
  failed: { bg: C.redBg, color: C.red, border: C.redBorder },
  accepted: { bg: C.blueBg, color: C.blue, border: C.blueBorder },
  declined: { bg: C.redBg, color: C.red, border: C.redBorder },
  active: { bg: C.greenBg, color: C.green, border: C.greenBorder },
  inactive: { bg: "hsl(240,3.7%,12%)", color: C.muted, border: "hsl(240,3.7%,18%)" },
  low: { bg: C.redBg, color: C.red, border: C.redBorder },
  ok: { bg: C.greenBg, color: C.green, border: C.greenBorder },
  admin: { bg: C.purpleBg, color: C.purple, border: C.purpleBorder },
  staff: { bg: C.blueBg, color: C.blue, border: C.blueBorder },
  customer: { bg: C.greenBg, color: C.green, border: C.greenBorder },
  "dine-in": { bg: C.yellowBg, color: C.yellow, border: C.yellowBorder },
  "take-out": { bg: "hsl(199,89%,8%)", color: "hsl(199,89%,60%)", border: "hsl(199,89%,16%)" },
  online: { bg: C.purpleBg, color: C.purple, border: C.purpleBorder },
  stock_in: { bg: C.greenBg, color: C.green, border: C.greenBorder },
  stock_out: { bg: C.redBg, color: C.red, border: C.redBorder },
};
